using PaymentGateway.Domain.Enums;

namespace PaymentGateway.Application.Common;

/// <summary>
/// External acquirer client boundary. The simulator implements this with configurable failure modes.
/// Recovery uses GetAuthorizationStatusAsync to resolve Unknown-state payments WITHOUT re-authorizing.
/// </summary>
public interface IAcquirerClient
{
    /// <summary>
    /// Request a new authorization from the acquirer. The idempotency key is generated by the gateway
    /// (derived from the payment ID) so recovery can query the same authorization later if the original
    /// response is lost. NEVER call this twice with the same key for the same payment — the acquirer
    /// must treat the key as idempotent and return the original result if seen again.
    /// </summary>
    Task<AcquirerAuthorization> AuthorizeAsync(AcquirerAuthorizationRequest request, CancellationToken cancellationToken);

    /// <summary>
    /// Query the outcome of a previously-sent authorization by the gateway-supplied idempotency key.
    /// Used by the recovery worker to resolve Unknown-state payments without re-authorizing.
    /// </summary>
    Task<AcquirerAuthorization> GetAuthorizationStatusAsync(string idempotencyKey, CancellationToken cancellationToken);

    /// <summary>
    /// Request a refund for a previously authorized payment. The original acquirer reference ties the
    /// refund back to the original authorization on the acquirer side.
    /// </summary>
    Task<AcquirerRefundResult> RefundAsync(AcquirerRefundRequest request, CancellationToken cancellationToken);
}

/// <summary>
/// Request to the acquirer to authorize a payment. CardToken is a simulator-only test reference;
/// real card numbers or CVV are never stored or logged anywhere in the system.
/// </summary>
public sealed record AcquirerAuthorizationRequest
{
    public required Guid PaymentId { get; init; }

    public required decimal Amount { get; init; }

    public required string Currency { get; init; }

    public required string CardToken { get; init; }

    public required string IdempotencyKey { get; init; }
}

/// <summary>
/// Acquirer response to an authorization request. Outcome distinguishes known success, known decline,
/// and unknown (timeout / no record). The recovery worker uses Outcome to drive safe state transitions.
/// </summary>
public sealed record AcquirerAuthorization
{
    public required string AuthCode { get; init; }

    public required string AcquirerReference { get; init; }

    public required AcquirerOutcome Outcome { get; init; }

    public string? DeclineReason { get; init; }
}

public sealed record AcquirerRefundRequest
{
    public required Guid PaymentId { get; init; }

    public required Guid RefundId { get; init; }

    public required string OriginalAcquirerReference { get; init; }

    public required decimal Amount { get; init; }

    public required string Currency { get; init; }

    public required string IdempotencyKey { get; init; }
}

public sealed record AcquirerRefundResult
{
    public required string? RefundReference { get; init; }

    public required AcquirerOutcome Outcome { get; init; }

    public string? DeclineReason { get; init; }
}
